repos:
-   repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 0.4.0
    hooks:
    -   id: sync_with_poetry

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/python-poetry/poetry
    rev: 1.4.2
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]